defaults: &defaults
  default_user_name: testTLX
  default_email_from: rakshassa@gmail.com
  rfq_contact_role: 4
  #default_email_from: purchasing@tlxtech.com
  #default_user_name: testVendor1

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults	